### ISSUE TITLE
where's tutorial ?

### ISSUE THREAD

**Issue by salRoid** [kybrdbnd/django-rest-tutorial#1]

**Comment by kybrdbnd** [comment]
i just started it, it will take time

**Comment by salRoid** [comment]
Then please do it in private when done then make it public 🍼

**Comment by kybrdbnd** [comment]
due to availability of the resources i cant make it private, if you are really interested in the particular repo, then kindly check it after few weeks

**Comment by salRoid** [comment]
unavailability ?
